import Link from "next/link";
import { ContactForm } from "@/components/contact-form";
import { PageIntro } from "@/components/page-intro";
import { SectionContainer } from "@/components/section-container";
import { SITE_CONFIG } from "@/config/site";
import { createMetadata } from "@/lib/metadata";

export const metadata = createMetadata("Få ett kostnadsfritt förslag", "Berätta kort om företaget och få ett tydligt nästa steg för en modern hemsida.", { pathname: "/kontakt" });

export default function ContactPage() { return <><PageIntro eyebrow="Kostnadsfritt första steg" title="Berätta vad företaget behöver, så tar vi det därifrån." description="Du behöver inte ha texter, bilder eller sidstruktur färdiga. Några meningar om verksamheten och nuläget räcker för ett första svar." /><section className="pb-12"><SectionContainer><div className="grid gap-8 lg:grid-cols-[0.72fr_1.28fr]"><aside className="space-y-6"><div className="rounded-[2rem] bg-[#173f35] p-8 text-white"><p className="text-xs font-bold tracking-[0.2em] text-[#f3b89f] uppercase">Direktkontakt</p><div className="mt-5 space-y-2 text-sm leading-7 text-white/72"><p><a href={`mailto:${SITE_CONFIG.contact.email}`}>{SITE_CONFIG.contact.email}</a></p><p><a href={SITE_CONFIG.contact.phoneHref}>{SITE_CONFIG.contact.phoneDisplay}</a></p><p>Hela processen genomförs digitalt</p></div><p className="mt-6 text-sm leading-7 text-white/60">Jag återkommer normalt inom en arbetsdag.</p></div><div className="rounded-[2rem] border border-[#173f35]/10 bg-white/60 p-7"><h2 className="text-xl font-semibold text-[#173f35]">Bra att nämna</h2><ul className="mt-5 space-y-3 text-sm leading-6 text-[#617169]"><li>Vad företaget erbjuder</li><li>Om en hemsida finns idag</li><li>Vad besökaren främst ska göra</li><li>Ungefär när sidan behövs</li></ul></div></aside><div className="rounded-[2.25rem] border border-[#173f35]/10 bg-[#fffdf8] p-7 md:p-10"><h2 className="text-3xl font-semibold tracking-[-0.04em] text-[#173f35]">Få ett första förslag</h2><p className="mt-4 text-sm leading-7 text-[#617169]">Fälten är medvetet få. Uppgifterna används bara för att besvara din förfrågan. Läs mer i <Link href="/integritet" className="font-semibold text-[#173f35] underline decoration-[#e86f44] underline-offset-4">integritetspolicyn</Link>.</p><div className="mt-8"><ContactForm /></div></div></div></SectionContainer></section></>; }
