import Link from "next/link";
import { CTABlock } from "@/components/cta-block";
import { Breadcrumbs } from "@/components/marketing/breadcrumbs";
import { PageIntro } from "@/components/page-intro";
import { SectionContainer } from "@/components/section-container";
import { SITE_CONFIG } from "@/config/site";
import { createMetadata } from "@/lib/metadata";
import { services } from "@/lib/site";

export const metadata = createMetadata("Hemsida till företag – paket och priser", "Jämför tydliga hemsidepaket för företag med fast pris från 2 995 kr exklusive moms.", { pathname: "/tjanster" });

export default function ServicesPage() {
  return <><Breadcrumbs items={[{ label: "Hem", href: "/" }, { label: "Paket" }]} />
    <PageIntro eyebrow="Paket och priser" title="En tydlig omfattning gör både arbetet och beslutet enklare." description="Välj en fokuserad ensideshemsida eller en större företagswebb. Introduktionspriserna gäller den beskrivna omfattningen och anges exklusive moms." />
    <section className="pb-12"><SectionContainer><div className="grid gap-6 lg:grid-cols-3">{services.map((service, index) => <article key={service.slug} className={`flex flex-col rounded-[2.25rem] border p-7 md:p-8 ${index === 1 ? "border-[#e86f44] bg-[#e86f44] text-white" : "border-[#173f35]/10 bg-white/65 text-[#173f35]"}`}><p className={`text-xs font-bold tracking-[0.16em] uppercase ${index === 1 ? "text-white/70" : "text-[#e86f44]"}`}>{service.label}</p><h2 className="mt-5 text-3xl font-semibold tracking-[-0.04em]">{service.title}</h2><p className={`mt-4 min-h-24 text-sm leading-7 ${index === 1 ? "text-white/75" : "text-[#617169]"}`}>{service.summary}</p><p className="mt-6 text-4xl font-semibold tracking-[-0.05em]">{service.price}<span className={`ml-1 text-sm tracking-normal ${index === 1 ? "text-white/60" : "text-[#617169]"}`}>{service.suffix}</span></p><p className={`mt-1 text-xs ${index === 1 ? "text-white/55" : "text-[#75827c]"}`}>exklusive moms</p><ul className="mt-7 flex-1 space-y-3">{service.included.slice(0, 5).map((item) => <li key={item} className={`flex gap-3 text-sm leading-6 ${index === 1 ? "text-white/80" : "text-[#52645b]"}`}><span aria-hidden="true">✓</span>{item}</li>)}</ul><Link href={service.href} className={`mt-8 rounded-full px-5 py-3 text-center text-sm font-semibold ${index === 1 ? "bg-white text-[#173f35]" : "bg-[#173f35] text-white"}`}>Se hela omfattningen</Link></article>)}</div><div className="mt-8 grid gap-6 rounded-[2rem] border border-[#173f35]/10 bg-white/55 p-6 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-xs font-bold tracking-[0.16em] text-[#e86f44] uppercase">Begränsat pilotpaket</p><h2 className="mt-2 text-xl font-semibold text-[#173f35]">Altura Mini · 2 995 kr exklusive moms</h2><p className="mt-2 text-sm leading-7 text-[#617169]">För företag som har färdiga texter och bilder och vill utgå från en fast grundlayout.</p></div><Link href="/mini" className="rounded-full border border-[#173f35]/20 px-5 py-3 text-center text-sm font-semibold text-[#173f35] transition hover:bg-[#173f35] hover:text-white">Se pilotpaketet</Link></div><div className="mt-8 rounded-[1.5rem] border border-[#173f35]/10 bg-white/55 p-6 text-sm leading-7 text-[#617169]"><strong className="text-[#173f35]">Bra att veta:</strong> E-handel, specialbyggda bokningssystem, avancerade integrationer, omfattande textproduktion och större varumärkesarbeten ingår inte i paketen. Om ditt behov ligger utanför omfattningen får du veta det innan något arbete startar.</div></SectionContainer></section>
    <CTABlock title="Osäker på vilket paket som passar?" description="Beskriv företaget och vad kunderna behöver kunna göra på sidan, så föreslår jag en rimlig nivå utan kostnad." primary={{ href: "/kontakt", label: SITE_CONFIG.cta.primary }} secondary={{ href: "/exempel", label: "Se exempel" }} />
  </>;
}
