import { WebsitePreview } from "@/components/marketing/website-preview";
import { CTABlock } from "@/components/cta-block";
import { PageIntro } from "@/components/page-intro";
import { SectionContainer } from "@/components/section-container";
import { createMetadata } from "@/lib/metadata";
import { demoProjects } from "@/lib/site";

export const metadata = createMetadata("Exempel på hemsidor", "Tre tydligt märkta demokoncept för målare, konsultbolag och salong.", { pathname: "/exempel" });

export default function ExamplesPage() { return <><PageIntro eyebrow="Demokoncept" title="Så olika kan en tydlig företagshemsida kännas." description="Exemplen är koncept framtagna för att visa möjlig designnivå. De representerar inte riktiga kunder, omdömen eller uppnådda resultat." /><section className="pb-12"><SectionContainer><div className="space-y-12">{demoProjects.map((project, index) => <article key={project.slug} className={`grid items-center gap-8 lg:grid-cols-2 ${index % 2 ? "lg:[&>*:first-child]:order-2" : ""}`}><WebsitePreview {...project} /><div className="max-w-xl"><p className="text-xs font-bold tracking-[0.2em] text-[#e86f44] uppercase">{project.label} · {project.industry}</p><h2 className="mt-5 text-4xl font-semibold tracking-[-0.05em] text-[#173f35]">{project.name}</h2><p className="mt-5 text-base leading-7 text-[#617169]">Konceptet visar hur färg, typografi och struktur kan anpassas efter bransch utan att göra sidan svår att använda. Leveransen fokuserar på ett tydligt budskap, mobil vy och enkel kontakt.</p><div className="mt-6 flex flex-wrap gap-2">{["Mobilanpassad", "Tydlig CTA", "Eget uttryck"].map((tag) => <span key={tag} className="rounded-full border border-[#173f35]/10 bg-white/60 px-3 py-2 text-xs font-medium text-[#53635c]">{tag}</span>)}</div></div></article>)}</div></SectionContainer></section><CTABlock title="Vill du se ett förslag för just din verksamhet?" description="Berätta kort om företaget. Ett första samtal och förslag är kostnadsfritt och utan bindning." primary={{ href: "/kontakt", label: "Få ett kostnadsfritt förslag" }} secondary={{ href: "/tjanster", label: "Se paket" }} /></>; }
