import Link from "next/link";
import { CTABlock } from "@/components/cta-block";
import { PageIntro } from "@/components/page-intro";
import { SectionContainer } from "@/components/section-container";
import { SITE_CONFIG } from "@/config/site";
import { createMetadata } from "@/lib/metadata";

export const metadata = createMetadata("Om Altura Nova", "Lär känna Albin Holmberg och Altura Nova, en personlig webbstudio som arbetar helt digitalt.", { pathname: "/om" });

const principles = [
  { title: "Tydligt före tekniskt", text: "Besökaren ska förstå företaget och nästa steg. Tekniken ska stödja det, inte stå i vägen." },
  { title: "Samma kontakt hela vägen", text: "Du pratar med personen som faktiskt strukturerar, bygger och kvalitetssäkrar sidan." },
  { title: "Rätt omfattning från början", text: "Paketet ska lösa ett verkligt behov utan att växa till ett onödigt stort och dyrt projekt." },
];

export default function AboutPage() { return <><PageIntro eyebrow="Om Altura Nova" title="En personlig webbstudio för företag som vill ha något tydligt, modernt och genomtänkt." description="Altura Nova drivs av Albin Holmberg. Hela processen kan genomföras digitalt, oavsett var ditt företag finns." /><section className="pb-12"><SectionContainer><div className="grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><div className="rounded-[2.25rem] bg-[#173f35] p-8 text-white md:p-10"><p className="text-xs font-bold tracking-[0.2em] text-[#f3b89f] uppercase">Bakom Altura Nova</p><h2 className="mt-5 text-4xl font-semibold tracking-[-0.05em]">Albin Holmberg</h2><p className="mt-6 text-base leading-8 text-white/72">Jag gillar kombinationen av tydlig kommunikation, genomtänkt design och teknik som bara fungerar. Altura Nova finns för företag som vill ha den kombinationen utan ett stort byråmaskineri.</p><p className="mt-4 text-base leading-8 text-white/72">Mitt mål är att du ska förstå processen, veta vad som ingår och känna att hemsidan faktiskt speglar nivån på ditt företag.</p><div className="mt-8 text-sm leading-7 text-white/65"><p>{SITE_CONFIG.contact.email}</p><p>{SITE_CONFIG.contact.phoneDisplay}</p><p>Hela processen genomförs digitalt</p></div></div><div className="rounded-[2.25rem] border border-[#173f35]/10 bg-white/65 p-8 md:p-10"><p className="text-xs font-bold tracking-[0.2em] text-[#e86f44] uppercase">Arbetssätt</p><div className="mt-6 space-y-5">{principles.map((item, index) => <article key={item.title} className="grid grid-cols-[auto_1fr] gap-4 rounded-[1.5rem] bg-[#eef2ec] p-5"><span className="text-xs font-bold text-[#e86f44]">0{index + 1}</span><div><h2 className="text-lg font-semibold text-[#173f35]">{item.title}</h2><p className="mt-2 text-sm leading-7 text-[#617169]">{item.text}</p></div></article>)}</div><p className="mt-6 text-sm leading-7 text-[#617169]">Vill du se vad jag kan skapa? Utforska de <Link href="/exempel" className="font-semibold text-[#173f35] underline decoration-[#e86f44] underline-offset-4">tydligt märkta demokoncepten</Link>.</p></div></div></SectionContainer></section><CTABlock title="Ska vi hitta rätt upplägg för ditt företag?" description="Ett kort första samtal räcker för att avgöra vilket paket som passar, eller om du behöver en annan lösning." primary={{ href: "/kontakt", label: SITE_CONFIG.cta.primary }} secondary={{ href: "/tjanster", label: "Se paket" }} /></>; }
